version: "3.8"

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
  
  celery:
    build: .
    container_name: celery_worker
    command: celery -A NGL worker --loglevel=info
    depends_on:
      - redis
      - web
    
  app:
    build: .
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn NGL.wsgi:application --bind 0.0.0.0:8000"

  
