# Generated by Django 4.2.15 on 2024-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0002_supportmessage_response_supportmessage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_images/'),
        ),
    ]
