# Generated by Django 4.2.15 on 2024-10-11 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в формате: +375xxxxxxxxx (9 цифр после +375).', regex='^\\+375\\d{9}$')]),
        ),
    ]
