# Generated by Django 4.2.15 on 2024-10-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_tutor_groups_remove_tutor_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
    ]
