# Generated by Django 4.2.15 on 2024-10-16 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Введите номер телефона в формате: +375xxxxxxxxx (9 цифр после +375).', regex='^\\+375\\d{9}$')]),
        ),
    ]
