# Generated by Django 4.2.15 on 2024-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_audience', models.CharField(choices=[('для себя', 'Для себя'), ('для ребенка', 'Для ребенка'), ('для семьи', 'Для семьи')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('мужчина', 'Мужчина'), ('женщина', 'Женщина'), ('не важно', 'Не важно')], max_length=10)),
                ('consultation_count', models.CharField(choices=[('1-2', '1-2'), ('решу позже', 'Решу после первой консультации')], max_length=20)),
                ('meeting_format', models.CharField(choices=[('онлайн', 'Онлайн'), ('лично', 'Лично')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
