# Generated by Django 4.2.15 on 2024-10-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_userconsultation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsultation',
            name='user',
        ),
    ]
